include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - flutter-facebook-auth/**/example/**
    - flutter-facebook-auth/**/examples/**
    - flutter-facebook-auth/**/test/**
    - "**/example/**"
    - "**/examples/**"
    - "**/test/**"

linter:
  rules:
    prefer_const_constructors: true
    avoid_print: true
    always_declare_return_types: true