// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKLKKDVWx6kS0q8PvaCUp51g-S3DDhAlw',
    appId: '1:176311148983:web:5e9b9b9fbdc00f7268c832',
    messagingSenderId: '176311148983',
    projectId: 'twenty-nine-card-game',
    authDomain: 'twenty-nine-card-game.firebaseapp.com',
    storageBucket: 'twenty-nine-card-game.firebasestorage.app',
    measurementId: 'G-2BPHVBWVH0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW4i4d4IP8M6nOcKzWZ-BisvibfN6qcqM',
    appId: '1:176311148983:android:09675788ce711e5e68c832',
    messagingSenderId: '176311148983',
    projectId: 'twenty-nine-card-game',
    storageBucket: 'twenty-nine-card-game.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdpsfVdaxHis2pKiVlQJIcO_UCq6LHszg',
    appId: '1:176311148983:ios:77ab77c3283a67fd68c832',
    messagingSenderId: '176311148983',
    projectId: 'twenty-nine-card-game',
    storageBucket: 'twenty-nine-card-game.firebasestorage.app',
    iosBundleId: 'com.example.twentyNineCardGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdpsfVdaxHis2pKiVlQJIcO_UCq6LHszg',
    appId: '1:176311148983:ios:77ab77c3283a67fd68c832',
    messagingSenderId: '176311148983',
    projectId: 'twenty-nine-card-game',
    storageBucket: 'twenty-nine-card-game.firebasestorage.app',
    iosBundleId: 'com.example.twentyNineCardGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKLKKDVWx6kS0q8PvaCUp51g-S3DDhAlw',
    appId: '1:176311148983:web:9336712e791993f168c832',
    messagingSenderId: '176311148983',
    projectId: 'twenty-nine-card-game',
    authDomain: 'twenty-nine-card-game.firebaseapp.com',
    storageBucket: 'twenty-nine-card-game.firebasestorage.app',
    measurementId: 'G-HSKE5EPW21',
  );
}
