import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';

import 'firebase_options.dart'; // generated by flutterfire configure
import 'services/firebase_service.dart';
import 'services/presence_service.dart';          // abstract
import 'services/presence_service_impl.dart';    // FirebasePresenceService
import 'services/room_service.dart';             // abstract
import 'services/room_service_impl.dart';        // FirestoreRoomService
import 'screens/main_menu.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase with platform-specific options
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // In production, pass your real implementations here
  runApp(
    TwentyNineApp(
      firebaseService: FirebaseService(),          
      presenceService: FirebasePresenceService(),  
      roomService: FirestoreRoomService(),         
    ),
  );
}

class TwentyNineApp extends StatelessWidget {
  final FirebaseService firebaseService;
  final PresenceService presenceService;
  final RoomService roomService;

  /// In production you must pass real implementations.
  /// In tests you can pass fakes:
  ///   TwentyNineApp(
  ///     firebaseService: fakeService,
  ///     presenceService: fakePresence,
  ///     roomService: fakeRoom,
  ///   )
  const TwentyNineApp({
    super.key,
    required this.firebaseService,
    required this.presenceService,
    required this.roomService,
  });

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Twenty Nine',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(primarySwatch: Colors.blue),
      home: MainMenu(
        firebaseService: firebaseService,
        presenceService: presenceService,
        roomService: roomService,
      ),
    );
  }
}